kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: production
spec:
  ports: 
    - port: 5432
      targetPort: 5432

---

kind: Endpoints
apiVersion: v1
metadata:
  name: postgres
  namespace: production
subsets:
  - addresses:
      - ip: 3.65.142.85
    ports:
      - port: 5432