import { Container } from "@chakra-ui/react";
import Head from "next/head";


export default function LayoutBase({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Base</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          {children}
        </Container>
      </main>
    </>
  )
}