import { Box, Container } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import DashboardSidebar from "~/components/DashboardSidebar";
import Navbar from "~/components/Navbar";

export default function LayoutBase({ children }: { children: React.ReactNode }) {

  const router = useRouter();

  const isDashboard = router.pathname.startsWith("/dashboard");

  return (
    <>
      <Head>
        <title>Base</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main style={{ height: "calc(100% - 97px)", display: "flex" }}>
        {isDashboard && <DashboardSidebar />}
        <Box  h="full" w="full">
          {children}
        </Box>
      </main>
    </>
  )
}