name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/webapp:latest
        build-args: |
          SKIP_ENV_VALIDATION=1
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/webapp:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/webapp:cache,mode=max
